### ISSUE TITLE
[Question] About the project

### ISSUE THREAD

**Issue by grantcarthew** [buckless/requelize#25]
@gjuchault A couple of questions:

- What's the current status of the project?
- Is this a personal project or are you funded?
- What is your expected support strategy?

**Comment by gjuchault** [comment]
* The project is alive and used only on one professional project that I work on. I doubt we can say that is production-ready and let's say it has been a replacement for Thinky for a few months now and it's working well
* It is a personal project, non-funded
* My plan was to make it to fill our needs (3-way relationships and `.sync()`), and then extend it if we ever need something. I will be glad to try to implement stuff if anyone starts having interest on this, and more than happy to merge pull-requests

**Comment by grantcarthew** [comment]
I haven't had a close look yet Gabriel. Is there a migration path?

**Comment by gjuchault** [comment]
There is none (yet ?)

Mainly what I've done to get my project going from thinky to requelize:
- Rethink model organisation if you want to use 3-way relationships
- Move all thinky definitions to joi definitions. Also change a bit your `preSave` stuff to the requelize hook system (no `this`, promise-enabled)
- Before starting http server (or anytime you want), use `requelize.sync().then(` so that you ensure DB is there
- If you're handling thinky errors, they are combined to one RequelizeError
- Replace `getJoin` by `embed`
- Replace `execute()` by `parse(false)`
- If you use feeds and also like Observables, use `.feed()`

That should be it

Again I'd like to warn you before you starting work on this : I can't ensure that this is production-ready or that the API is not going to change some day. But, if you ever try it and have some issues/troubles migrating, I'd be glad to take a look

**Comment by grantcarthew** [comment]
Sounds good mate. I'm working on the front-end of my current project at the moment so am not going to touch the API yet. When I do I will revisit this.

**Comment by Extarys** [comment]
Great project, may try to implement this instead of rethink.

**Comment by jimjones26** [comment]
Hey, I am a bit of a noob and I have a few questions, hopefully it is ok to ask here? First, how to you handle making sure the shape of your in memory objects (using typescript interface perhaps) always matches your requelize models? Does it require having both requelize models and typescript interfaces, and just making sure manually that they match, or is there another easier approach? I ask in the context of trying to share models between back-end and front-end code. Also, do you have a small sample you could post? Thanks!

**Comment by gjuchault** [comment]
@jimjones26 
If the first question is : how do I make sure models that are being saved match models, then I use [joi](https://github.com/hapijs/joi) for this. If the first question is : how do I make sure data already in DB matches models, then I don't. Thinky does care about that, btw
I do not use Typescript interface, but you might want to try if you want. If you need some `.d.ts` file for the project, please fill up an issue and I'll do it when I have time.
You can find a lot of samples directly on the `README.md` file, or in the `test/` directory

**Comment by jimjones26** [comment]
Oh perfect, I never even thought to look in the test directories. Thanks!
